import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" bg-gray-200 dark:bg-indigo-950 ">
          <div className=" max-w-[1536px] sm:max-w-[475px] md:max-w-[640px] lg:max-w-[768px] xl:max-w-[1040px] 2xl:max-w-[1366px] mx-auto px-10 border-2 border-black min-h-[100vh] flex flex-col justify-between">
            <Navbar />
            {children}
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
